name: flutter_whisper_kit_example
description: "Demonstrates how to use the flutter_whisper_kit plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_whisper_kit:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
